"""empty message

Revision ID: 79f7b408149a
Revises: 0166c5d76019
Create Date: 2020-08-13 17:36:44.439388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f7b408149a'
down_revision = '0166c5d76019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('stack', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'stack')
    # ### end Alembic commands ###
