"""empty message

Revision ID: eaca96713dd2
Revises: 5c076f4f962c
Create Date: 2020-08-15 23:20:39.500284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaca96713dd2'
down_revision = '5c076f4f962c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
